# Generated by Django 4.0 on 2021-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Phoneno', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
